version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: deploy/scripts/install_dependencies.sh
      timeout: 600
      runas: root

  ApplicationStart:
    - location: deploy/scripts/start_docker.sh
      timeout: 600
      runas: root