version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app

hooks:
  BeforeInstall:
    - location: deploy/scripts/install_dependencies.sh
      timeout: 600
      runas: root

  ApplicationStart:
    - location: deploy/scripts/start_docker.sh
      timeout: 600
      runas: root

  ValidateService:
    - location: deploy/scripts/validate_service.sh
      timeout: 120
      runas: root